

version: '3.8'
networks: 
    todo-network:
        driver: bridge
        
volumes:
    mysql-data:
 
services:
    todo-application:
        image: todo-application-image:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo-application
        ports:
            - "8082:8081"
        depends_on:
            - mysql-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tododb
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=Nuvelabs123$
        networks: 
            - todo-network
    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=Nuvelabs123$
            - MYSQL_DATABASE=tododb
        ports:
            - "3307:3306"
        restart: always
        networks:
            - todo-network
        volumes: 
            - mysql-data:/var/lib/mysql
            
